### ISSUE TITLE
Build and Setup DAOS on single node VM and perform object operations

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-experiments#26]
- [x] Build DAOS from source
- [x] Install built DAOS and configure single node cluster
- [x] Create/Write/Read/Delete DAOS Objects
- [ ] Prepare document with steps/references for quickstart daos for CORTX team

**Comment by rajkumarpatel2602** [comment]
Done : First three steps practically are done and also created a document (https://github.com/Seagate/cortx-experiments/tree/rajkumarpatel2602-patch-1/daos%2Bcortx/docs) for cortx team to setup single node server and perform container creation part.

ToDo : Add screenshots

**Comment by johnbent** [comment]
@rajkumarpatel2602 , that's a nice looking document!  I assume you'll be creating a PR to merge it into the main when it is finished?

**Comment by rajkumarpatel2602** [comment]
Yes John. After completion I will raise PR to merge my changes into main.

**Comment by rajkumarpatel2602** [comment]
Daos setup document is updated and PR got merged.
