### ISSUE TITLE
DAOS to CORTX data movement using aws s3 cli

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-experiments#29]
- [x] Setup CORTX in single node VM
- [x] Setup DAOS in single node VM
- [x] Create bucket in Cortx using aws s3 cli
- [x] Create pool and containers in DAOS
- [x] Create test objects in Cortx and DAOS
- [x] Copy objects from S3 bucket in Cortx to DAOS using aws s3 cli 
- [x] Copy objects from DAOS source container to S3 bucket in Cortx using aws s3 cli 
- [x] Verify Target bucket and DAOS containers for copied objects in each step
- [x] Document the process in quickstart

**Comment by rajkumarpatel2602** [comment]
Steps covered :
1. acquired a VM for cortx single node deployment. deployed it and verified the installation using hctl status.

> [root@ssc-vm-2161 ~]# hctl status
> 
> Profile: 0x7000000000000001:0x1c
> 
> Data pools:
>     0x6f00000000000001:0x1d
> 
> Services:
>     srvnode-1  (RC)
>     [started]  hax        0x7200000000000001:0x6   192.168.29.186@tcp:12345:1:1
>     [started]  confd      0x7200000000000001:0x9   192.168.29.186@tcp:12345:2:1
>     [started]  ioservice  0x7200000000000001:0xc   192.168.29.186@tcp:12345:2:2
>     [started]  s3server   0x7200000000000001:0x16  192.168.29.186@tcp:12345:3:1
>     [unknown]  m0_client  0x7200000000000001:0x19  192.168.29.186@tcp:12345:4:1

2. acquired 1 more VM and installed daos using quickstart. 

3. installed s3 cli on daos node.

> [root@ssc-vm-2162 test_src]# aws s3 ls
> 2021-01-24 10:31:58 test-bucket
> [root@ssc-vm-2162 test_dest]#

added cortx node IP (s3.seagate.com) to /etc/hosts
added same credentials for access of cortx node inside ~/.aws/credentials file (after creating) on daos node.

4. Created 2 containers inside a pull and mount using dfuse at following location

/mnt/dfuse_data/test_src/
/mnt/dfuse_data/dest_src/ 

5. created fileA inside with some contents in container's dfuse directory test_src //

5. create test-bucket on cortx node using following command

> aws s3 mb s3://test-bucket

6. verified bucket list on daos node

> aws s3 ls 

7. copied fileA from /mnt/dfuse_data/test_src/ (dfuse location) to s3 bucket

> [root@ssc-vm-2162 test_src]# aws s3 cp fileA s3://test-bucket/

8. copied back file to dest_src from s3 bucket.

> [root@ssc-vm-2162 dest_src]# aws s3 cp s3://test-bucket/fileA  .

7. verified file contents inside dest_src

8. performed mv operation for the same and verified contents before and after.

**Comment by rajkumarpatel2602** [comment]
Steps are captured in the document and created a [PR draft](https://github.com/Seagate/cortx-experiments/pull/48). 
WIP.
