### ISSUE TITLE
CORTX-DAOS data movement using s3fs and mpifileutils

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-experiments#31]
- [ ] Setup CORTX in single node VM
- [ ] Setup DAOS in single node VM
- [ ] Create bucket in Cortx using aws s3 cli
- [ ] Create pool and containers in DAOS
- [ ] Create test objects in Cortx and DAOS
- [ ] Mount bucket using s3fs
- [ ] Copy objects from S3 bucket in Cortx to DAOS using mpifilutils (cortx-s3fs <--> daos-dfuse)
- [ ] Copy objects from DAOS source container to S3 bucket in Cortx  using mpifilutils (cortx-s3fs <--> daos-dfuse)
- [ ] Verify Target bucket and DAOS containers for copied objects in each step
- [ ] Document the process in quickstart

**Comment by hessio** [comment]
I think this is encapsulated in this page [https://github.com/Seagate/cortx-experiments/tree/main/daos-cortx](https://github.com/Seagate/cortx-experiments/tree/main/daos-cortx) @kaustubh-d can you provide an update on this?

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~744292] [~940197] [~757448] [~720600] 
not sure where this sits exactly, looks like a mix of deploy/setup and run time activity.  Does our most recent docs address this?

**Comment by hessio** [comment]
@kaustubh-d has left seagate and it looks like this [guide](https://github.com/Seagate/cortx-experiments/tree/main/daos-cortx ) covers most of what he wanted covered so we can close this issue for now and a new one can be opened if needed.

**Comment by hessio** [comment]
@kaustubh-d has left seagate and it looks like this [guide](https://github.com/Seagate/cortx-experiments/tree/main/daos-cortx ) covers most of what he wanted covered so we can close this issue for now and a new one can be opened if needed.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed and corresponding github issue is closed
