### ISSUE TITLE
CORTX - DAOS data movement using mpifileutils (S3 backend)

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-experiments#32]
Add support to mpifileutils for S3 backend and enable DAOS to CORTX-S3 data movement.

**Comment by hessio** [comment]
Hi @kaustubh-d  can you provide an update on this issue?

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~744292] [~532357] [~720600]
who takes up this stuff that was formerly in ADG realm?  (i think this fits there?)

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue as No work as we have moved from S3 to RGW
