### ISSUE TITLE
update interface in daos-cortx/docs/mpifileutils_setup.md

### ISSUE THREAD

**Issue by daltonbohning** [Seagate/cortx-experiments#41]
Instead of using:
```
--daos-src-pool
--daos-src-cont
--daos-dst-pool
--daos-dst-cont
```

daos paths are now represented by:
`daos://<pool_uuid>/<cont_uuid>[/<path>]`

A new optional parameter allows explicitly switching between the "DAOS" API and "DFS" API:
`--daos-api {DAOS, DFS}`
By default, POSIX type containers use he "DFS" API, and other containers use the "DAOS" API.
The difference is that the "DFS" API treats objects as files, whereas the "DAOS" API simply copies all objects in the container.

**Comment by daltonbohning** [comment]
@rajkumarpatel2602 This change was just merged by https://github.com/hpc/mpifileutils/pull/434

**Comment by rajkumarpatel2602** [comment]
Need to verify taking the most recent commit https://github.com/hpc/mpifileutils/pull/442 and with a object copy rather than container copy.
