### ISSUE TITLE
Wrong Links in the File 

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-experiments#47]
https://github.com/Seagate/cortx-experiments/tree/b4447e179bf87ca9a5b6b50b50c803ec0adcda38/S3/Full-Fake-TTFB/objective

**Comment by TechWriter-Mayur** [comment]
> 
> 
> https://github.com/Seagate/cortx-experiments/tree/b4447e179bf87ca9a5b6b50b50c803ec0adcda38/S3/Full-Fake-TTFB/objective

@raikrahul - Can you please let me know which are the links that are not accessible?

**Comment by johnbent** [comment]
Closing this.  It does link to an internal page.  We try not to do that but sometimes it is unavoidable.
