### ISSUE TITLE
Orphaned Page

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-experiments#72]
@rajkumarpatel2602 

Our main github page listing our integrations has a link for the DAOS organization which points to:

[https://github.com/Seagate/cortx-experiments/blob/main/daos-cortx/docs/datamovment_with_s3.md](https://github.com/Seagate/cortx-experiments/blob/main/daos-cortx/docs/datamovment_with_s3.md)

Is that the correct page that best describes the DAOS integration and enables the community to reproduce what you've done?

The reason that I ask is that I just approved a PR where you added a video link to this page:

[https://github.com/Seagate/cortx-experiments/blob/main/daos-cortx/docs/setup_robinhood_policy_engine.md](https://github.com/Seagate/cortx-experiments/blob/main/daos-cortx/docs/setup_robinhood_policy_engine.md)

The problem is that I cannot find any links to that second page from anywhere else in GitHub.  Do we need to add a link to the second page from the first page?  Or do we just need to change the link from the integration page to point to the second page?

By the way, our general rule for github is to avoid orphan pages.  An orphan page is a page that has useful information but which is not reachable via links from other existing documents.  So, if we ever add a new page we have to simultaneously add a link to that new page into an existing page.  In this case, I cannot find any links to this second page so I fear we accidentally created an orphan page.  How can we fix this?

**Comment by hessio** [comment]
Fixed 839e542

**Comment by hessio** [comment]
Fixed by 839e542

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~744292] [~532357] [~720600]
where does this live now?  Which team?

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

MOTR Team, [~211146]

FYI [~520479]

**Comment by cortx-admin** [comment]
> Amit Kapil commented in Jira Server:

this can be closed as per above comment I think.

**Comment by cortx-admin** [comment]
> Trupti Patil commented in Jira Server:

DAOS project was initially with Motr and then was eventually moved to ADG team.

[~535110], Would you like to get this ticket closed ?

CC: [~536285]

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue as corresponding github issue is Closed
