### ISSUE TITLE
Fix typos in Makefile of google_benchmark 

### ISSUE THREAD

**Issue by rajkumarpatel2602** [Seagate/cortx-experiments#75]
Makefile is not broken.

**Comment by hessio** [comment]
What is the status of this issue. I see the PR is able to be merged now, can you merge the PR and close this issue?

**Comment by hessio** [comment]
Hi @rajkumarpatel2602 what is the status of this issue?

**Comment by rajkumarpatel2602** [comment]
> Hi @rajkumarpatel2602 what is the status of this issue?

It was linked with #76. PR #76 now merged and hence this PR is closed now.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~940197] [~757448] [~729494] [~744292] [~747271] [~930816]

I suspect all our latest documentation supercedes anything here.  what next step here, if it can be closed who owns that?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue as corresponding github issue is Closed
